INSERT INTO category (category_name,description) VALUES ('Snacks','Perfect side dish for hot tea or cofee')
INSERT INTO category (category_name,description) VALUES ('HOT','Tea or cofee')
INSERT INTO category (category_name,description) VALUES ('Beverage','A soothing for summer')
INSERT INTO category (category_name,description) VALUES ('Dessert','Sweet for a starting a sweet relation')
INSERT INTO unit_of_messure (description) VALUES ('TeaSpoon')
INSERT INTO unit_of_messure (description) VALUES ('TableSpoon')
INSERT INTO unit_of_messure (description) VALUES ('Cup')
INSERT INTO unit_of_messure (description) VALUES ('Pinch')
INSERT INTO unit_of_messure (description) VALUES ('Ounce')
INSERT INTO unit_of_messure (description) VALUES ('Dash')